apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: svoyak
  namespace: svoyak
  labels:
    app: svoyak
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: registry.fedoraproject.org/f29/golang
    name: golang
    referencePolicy:
      type: Local
  - from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/ubi
    name: ubi8
    referencePolicy:
      type: Source
  - name: src
    referencePolicy:
      type: Source
  - name: bin
    referencePolicy:
      type: Source
