apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: svoyak
  name: svoyak-src
  namespace: svoyak
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: svoyak:src
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/vrutkovs/svoyak
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: svoyak:golang
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - github:
      secret: dbb3f5b90a1a1283
    type: GitHub
