kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: svoyak-pipeline
  namespace: svoyak
spec:
  source:
    git:
      uri: "https://github.com/vrutkovs/svoyak"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: manifests/Jenkinsfile
    type: JenkinsPipeline
